const products = [
    {
      id: 1,
      subject: "Maths",
      location: "Hall 1",
      stock: 5,
      space: 5,
      price: 283,
      image: "./img/math.webp",
      cartquantity: 0,
    },
    {
      id: 2,
      subject: "Biology",
      location: "Hall 9",
      stock: 5,
      space: 5,
      price: 182,
      image: "./img/biology.jpeg",
      cartquantity: 0,
    },
    {
      id: 3,
      subject: "Physics",
      location: "Hall 7",
      stock: 5,
      space: 5,
      price: 282,
      image: "./img/physics.webp",
      cartquantity: 0,
    },
    {
      id: 4,
      subject: "Chemistry",
      location: "Hall 4",
      stock: 5,
      space: 5,
      price: 131,
      image: "./img/chemistry.webp",
      cartquantity: 0,
    },
    {
      id: 5,
      subject: "Physical Education",
      location: "Hall 5",
      stock: 5,
      space: 5,
      price: 62,
      image: "./img/pe.webp",
      cartquantity: 0,
    },
    {
      id: 6,
      subject: "Economics",
      location: "Hall 6",
      stock: 5,
      space: 5,
      price: 137,
      image: "./img/economics.jpeg",
      cartquantity: 0,
    },
    {
      id: 7,
      subject: "Macronomics",
      location: "Hall 3",
      stock: 5,
      space: 5,
      price: 200,
      image: "./img/macronomics.webp",
      cartquantity: 0,
    },
    {
      id: 8,
      subject: "Finance",
      location: "Hall 8",
      stock: 5,
      space: 5,
      price: 137,
      image: "./img/finance.webp",
      cartquantity: 0,
    },
    {
      id: 9,
      subject: "Football",
      location: "Hall 2",
      stock: 5,
      space: 5,
      price: 137,
      image: "./img/football.jpeg",
      cartquantity: 0,
    },
    {
      id: 10,
      subject: "Basketball",
      location: "Hall 10",
      stock: 5,
      space: 5,
      price: 184,
      image: "./img/basketball.jpeg",
      cartquantity: 0,
    },
  ];

export default products;